import type { NextPage, GetServerSidePropsContext } from "next";
import Head from "next/head";
import { getSession } from "next-auth/react";

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create CrossPlotform App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main></main>
		</div>
	);
};



export default Home;
